// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event_EventType int32

const (
	Event_RESERVED      Event_EventType = 0
	Event_BLOCK_ADDED   Event_EventType = 1
	Event_EPOCH_STARTED Event_EventType = 2
	Event_VIEW_CHANGED  Event_EventType = 3
)

var Event_EventType_name = map[int32]string{
	0: "RESERVED",
	1: "BLOCK_ADDED",
	2: "EPOCH_STARTED",
	3: "VIEW_CHANGED",
}

var Event_EventType_value = map[string]int32{
	"RESERVED":      0,
	"BLOCK_ADDED":   1,
	"EPOCH_STARTED": 2,
	"VIEW_CHANGED":  3,
}

func (x Event_EventType) String() string {
	return proto.EnumName(Event_EventType_name, int32(x))
}

func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0, 0}
}

type Event struct {
	Type                 Event_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=Event_EventType" json:"type,omitempty"`
	Payload              *any.Any        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() Event_EventType {
	if m != nil {
		return m.Type
	}
	return Event_RESERVED
}

func (m *Event) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EpochStartedPayload struct {
	Epoch                int32    `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochStartedPayload) Reset()         { *m = EpochStartedPayload{} }
func (m *EpochStartedPayload) String() string { return proto.CompactTextString(m) }
func (*EpochStartedPayload) ProtoMessage()    {}
func (*EpochStartedPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EpochStartedPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochStartedPayload.Unmarshal(m, b)
}
func (m *EpochStartedPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochStartedPayload.Marshal(b, m, deterministic)
}
func (m *EpochStartedPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochStartedPayload.Merge(m, src)
}
func (m *EpochStartedPayload) XXX_Size() int {
	return xxx_messageInfo_EpochStartedPayload.Size(m)
}
func (m *EpochStartedPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochStartedPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EpochStartedPayload proto.InternalMessageInfo

func (m *EpochStartedPayload) GetEpoch() int32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type ViewChangedPayload struct {
	View                 int32    `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChangedPayload) Reset()         { *m = ViewChangedPayload{} }
func (m *ViewChangedPayload) String() string { return proto.CompactTextString(m) }
func (*ViewChangedPayload) ProtoMessage()    {}
func (*ViewChangedPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *ViewChangedPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChangedPayload.Unmarshal(m, b)
}
func (m *ViewChangedPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChangedPayload.Marshal(b, m, deterministic)
}
func (m *ViewChangedPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChangedPayload.Merge(m, src)
}
func (m *ViewChangedPayload) XXX_Size() int {
	return xxx_messageInfo_ViewChangedPayload.Size(m)
}
func (m *ViewChangedPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChangedPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChangedPayload proto.InternalMessageInfo

func (m *ViewChangedPayload) GetView() int32 {
	if m != nil {
		return m.View
	}
	return 0
}

func init() {
	proto.RegisterEnum("Event_EventType", Event_EventType_name, Event_EventType_value)
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*EpochStartedPayload)(nil), "EpochStartedPayload")
	proto.RegisterType((*ViewChangedPayload)(nil), "ViewChangedPayload")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x6d, 0x6d, 0xfd, 0x73, 0x3b, 0x35, 0xc6, 0x3d, 0x4c, 0x9f, 0x46, 0xf1, 0xa1, 0x20,
	0x64, 0x30, 0x3f, 0x41, 0xd7, 0x5c, 0x9c, 0x28, 0x76, 0xa4, 0xa5, 0x82, 0x2f, 0xa5, 0x75, 0xb1,
	0x1b, 0x8c, 0x26, 0x8c, 0xba, 0xd1, 0x2f, 0xe5, 0x67, 0x94, 0xa5, 0xce, 0xbd, 0x84, 0x9c, 0x73,
	0x7e, 0x9c, 0x7b, 0x2f, 0x78, 0x72, 0x23, 0xeb, 0x86, 0xe9, 0xb5, 0x6a, 0xd4, 0xdd, 0x6d, 0xa5,
	0x54, 0xb5, 0x92, 0x23, 0xa3, 0xca, 0xef, 0xaf, 0x51, 0x51, 0xb7, 0x5d, 0xe4, 0xff, 0x58, 0xe0,
	0xe2, 0x0e, 0xa5, 0xf7, 0xe0, 0x34, 0xad, 0x96, 0x03, 0x6b, 0x68, 0x05, 0x97, 0x63, 0xc2, 0x8c,
	0xdb, 0xbd, 0x69, 0xab, 0xa5, 0x30, 0x29, 0x65, 0x70, 0xaa, 0x8b, 0x76, 0xa5, 0x8a, 0xf9, 0xc0,
	0x1e, 0x5a, 0x81, 0x37, 0xee, 0xb3, 0xae, 0x9c, 0xed, 0xcb, 0x59, 0x58, 0xb7, 0x62, 0x0f, 0xf9,
	0x31, 0x9c, 0xff, 0x57, 0xd0, 0x1e, 0x9c, 0x09, 0x4c, 0x50, 0x64, 0xc8, 0xc9, 0x11, 0xbd, 0x02,
	0x6f, 0xf2, 0x1a, 0x47, 0x2f, 0x79, 0xc8, 0x39, 0x72, 0x62, 0xd1, 0x6b, 0xb8, 0xc0, 0x59, 0x1c,
	0x4d, 0xf3, 0x24, 0x0d, 0x45, 0x8a, 0x9c, 0xd8, 0x94, 0x40, 0x2f, 0x7b, 0xc6, 0xf7, 0x3c, 0x9a,
	0x86, 0x6f, 0x4f, 0xc8, 0xc9, 0xb1, 0xff, 0x00, 0x37, 0xa8, 0xd5, 0xe7, 0x22, 0x69, 0x8a, 0x75,
	0x23, 0xe7, 0xb3, 0x6e, 0x0e, 0xed, 0x83, 0x2b, 0x77, 0xb6, 0x59, 0xdf, 0x15, 0x9d, 0xf0, 0x03,
	0xa0, 0xd9, 0x52, 0x6e, 0xa3, 0x45, 0x51, 0x57, 0x07, 0x96, 0x82, 0xb3, 0x59, 0xca, 0xed, 0x1f,
	0x6a, 0xfe, 0x13, 0xe7, 0xc3, 0xd6, 0x65, 0x79, 0x62, 0x8e, 0x78, 0xfc, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x6c, 0xf0, 0xc5, 0xe0, 0x3e, 0x01, 0x00, 0x00,
}
