// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_HELLO_REQUEST  Message_MessageType = 0
	Message_HELLO_RESPONSE Message_MessageType = 1
	Message_EPOCH_START    Message_MessageType = 2
	Message_VOTE           Message_MessageType = 3
	Message_PROPOSAL       Message_MessageType = 4
	Message_BLOCK_REQUEST  Message_MessageType = 5
	Message_BLOCK_RESPONSE Message_MessageType = 6
	Message_TRANSACTION    Message_MessageType = 7
)

var Message_MessageType_name = map[int32]string{
	0: "HELLO_REQUEST",
	1: "HELLO_RESPONSE",
	2: "EPOCH_START",
	3: "VOTE",
	4: "PROPOSAL",
	5: "BLOCK_REQUEST",
	6: "BLOCK_RESPONSE",
	7: "TRANSACTION",
}

var Message_MessageType_value = map[string]int32{
	"HELLO_REQUEST":  0,
	"HELLO_RESPONSE": 1,
	"EPOCH_START":    2,
	"VOTE":           3,
	"PROPOSAL":       4,
	"BLOCK_REQUEST":  5,
	"BLOCK_RESPONSE": 6,
	"TRANSACTION":    7,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Error_ErrorCode int32

const (
	Error_NOT_FOUND   Error_ErrorCode = 0
	Error_BAD_REQUEST Error_ErrorCode = 1
)

var Error_ErrorCode_name = map[int32]string{
	0: "NOT_FOUND",
	1: "BAD_REQUEST",
}

var Error_ErrorCode_value = map[string]int32{
	"NOT_FOUND":   0,
	"BAD_REQUEST": 1,
}

func (x Error_ErrorCode) String() string {
	return proto.EnumName(Error_ErrorCode_name, int32(x))
}

func (Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7, 0}
}

type Transaction_Type int32

const (
	Transaction_PAYMENT  Transaction_Type = 0
	Transaction_SLASHING Transaction_Type = 1
)

var Transaction_Type_name = map[int32]string{
	0: "PAYMENT",
	1: "SLASHING",
}

var Transaction_Type_value = map[string]int32{
	"PAYMENT":  0,
	"SLASHING": 1,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}

func (Transaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13, 0}
}

type Message struct {
	Type                 Message_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=Message_MessageType" json:"type,omitempty"`
	Payload              *any.Any            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_MessageType {
	if m != nil {
		return m.Type
	}
	return Message_HELLO_REQUEST
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HelloPayload struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TopBlockHeight       int32    `protobuf:"varint,2,opt,name=topBlockHeight,proto3" json:"topBlockHeight,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloPayload) Reset()         { *m = HelloPayload{} }
func (m *HelloPayload) String() string { return proto.CompactTextString(m) }
func (*HelloPayload) ProtoMessage()    {}
func (*HelloPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *HelloPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloPayload.Unmarshal(m, b)
}
func (m *HelloPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloPayload.Marshal(b, m, deterministic)
}
func (m *HelloPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloPayload.Merge(m, src)
}
func (m *HelloPayload) XXX_Size() int {
	return xxx_messageInfo_HelloPayload.Size(m)
}
func (m *HelloPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloPayload.DiscardUnknown(m)
}

var xxx_messageInfo_HelloPayload proto.InternalMessageInfo

func (m *HelloPayload) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *HelloPayload) GetTopBlockHeight() int32 {
	if m != nil {
		return m.TopBlockHeight
	}
	return 0
}

func (m *HelloPayload) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type EpochStartPayload struct {
	// Types that are valid to be assigned to Body:
	//	*EpochStartPayload_Cert
	//	*EpochStartPayload_GenesisSignature
	Body                 isEpochStartPayload_Body `protobuf_oneof:"body"`
	Signature            []byte                   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	EpochNumber          int32                    `protobuf:"varint,4,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EpochStartPayload) Reset()         { *m = EpochStartPayload{} }
func (m *EpochStartPayload) String() string { return proto.CompactTextString(m) }
func (*EpochStartPayload) ProtoMessage()    {}
func (*EpochStartPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *EpochStartPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochStartPayload.Unmarshal(m, b)
}
func (m *EpochStartPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochStartPayload.Marshal(b, m, deterministic)
}
func (m *EpochStartPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochStartPayload.Merge(m, src)
}
func (m *EpochStartPayload) XXX_Size() int {
	return xxx_messageInfo_EpochStartPayload.Size(m)
}
func (m *EpochStartPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochStartPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EpochStartPayload proto.InternalMessageInfo

type isEpochStartPayload_Body interface {
	isEpochStartPayload_Body()
}

type EpochStartPayload_Cert struct {
	Cert *QuorumCertificate `protobuf:"bytes,1,opt,name=cert,proto3,oneof"`
}

type EpochStartPayload_GenesisSignature struct {
	GenesisSignature []byte `protobuf:"bytes,2,opt,name=genesisSignature,proto3,oneof"`
}

func (*EpochStartPayload_Cert) isEpochStartPayload_Body() {}

func (*EpochStartPayload_GenesisSignature) isEpochStartPayload_Body() {}

func (m *EpochStartPayload) GetBody() isEpochStartPayload_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *EpochStartPayload) GetCert() *QuorumCertificate {
	if x, ok := m.GetBody().(*EpochStartPayload_Cert); ok {
		return x.Cert
	}
	return nil
}

func (m *EpochStartPayload) GetGenesisSignature() []byte {
	if x, ok := m.GetBody().(*EpochStartPayload_GenesisSignature); ok {
		return x.GenesisSignature
	}
	return nil
}

func (m *EpochStartPayload) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EpochStartPayload) GetEpochNumber() int32 {
	if m != nil {
		return m.EpochNumber
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EpochStartPayload) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EpochStartPayload_Cert)(nil),
		(*EpochStartPayload_GenesisSignature)(nil),
	}
}

type ProposalPayload struct {
	Cert                 *QuorumCertificate `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Block                *Block             `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProposalPayload) Reset()         { *m = ProposalPayload{} }
func (m *ProposalPayload) String() string { return proto.CompactTextString(m) }
func (*ProposalPayload) ProtoMessage()    {}
func (*ProposalPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *ProposalPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalPayload.Unmarshal(m, b)
}
func (m *ProposalPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalPayload.Marshal(b, m, deterministic)
}
func (m *ProposalPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalPayload.Merge(m, src)
}
func (m *ProposalPayload) XXX_Size() int {
	return xxx_messageInfo_ProposalPayload.Size(m)
}
func (m *ProposalPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalPayload proto.InternalMessageInfo

func (m *ProposalPayload) GetCert() *QuorumCertificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *ProposalPayload) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ProposalPayload) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type VotePayload struct {
	Cert                 *QuorumCertificate `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Header               *BlockHeader       `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VotePayload) Reset()         { *m = VotePayload{} }
func (m *VotePayload) String() string { return proto.CompactTextString(m) }
func (*VotePayload) ProtoMessage()    {}
func (*VotePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *VotePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotePayload.Unmarshal(m, b)
}
func (m *VotePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotePayload.Marshal(b, m, deterministic)
}
func (m *VotePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotePayload.Merge(m, src)
}
func (m *VotePayload) XXX_Size() int {
	return xxx_messageInfo_VotePayload.Size(m)
}
func (m *VotePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_VotePayload.DiscardUnknown(m)
}

var xxx_messageInfo_VotePayload proto.InternalMessageInfo

func (m *VotePayload) GetCert() *QuorumCertificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *VotePayload) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *VotePayload) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type BlockRequestPayload struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequestPayload) Reset()         { *m = BlockRequestPayload{} }
func (m *BlockRequestPayload) String() string { return proto.CompactTextString(m) }
func (*BlockRequestPayload) ProtoMessage()    {}
func (*BlockRequestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *BlockRequestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequestPayload.Unmarshal(m, b)
}
func (m *BlockRequestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequestPayload.Marshal(b, m, deterministic)
}
func (m *BlockRequestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequestPayload.Merge(m, src)
}
func (m *BlockRequestPayload) XXX_Size() int {
	return xxx_messageInfo_BlockRequestPayload.Size(m)
}
func (m *BlockRequestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequestPayload proto.InternalMessageInfo

func (m *BlockRequestPayload) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockRequestPayload) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockResponsePayload struct {
	// Types that are valid to be assigned to Response:
	//	*BlockResponsePayload_Blocks
	//	*BlockResponsePayload_ErrorCode
	Response             isBlockResponsePayload_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *BlockResponsePayload) Reset()         { *m = BlockResponsePayload{} }
func (m *BlockResponsePayload) String() string { return proto.CompactTextString(m) }
func (*BlockResponsePayload) ProtoMessage()    {}
func (*BlockResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *BlockResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponsePayload.Unmarshal(m, b)
}
func (m *BlockResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponsePayload.Marshal(b, m, deterministic)
}
func (m *BlockResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponsePayload.Merge(m, src)
}
func (m *BlockResponsePayload) XXX_Size() int {
	return xxx_messageInfo_BlockResponsePayload.Size(m)
}
func (m *BlockResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponsePayload proto.InternalMessageInfo

type isBlockResponsePayload_Response interface {
	isBlockResponsePayload_Response()
}

type BlockResponsePayload_Blocks struct {
	Blocks *Blocks `protobuf:"bytes,1,opt,name=blocks,proto3,oneof"`
}

type BlockResponsePayload_ErrorCode struct {
	ErrorCode *Error `protobuf:"bytes,2,opt,name=errorCode,proto3,oneof"`
}

func (*BlockResponsePayload_Blocks) isBlockResponsePayload_Response() {}

func (*BlockResponsePayload_ErrorCode) isBlockResponsePayload_Response() {}

func (m *BlockResponsePayload) GetResponse() isBlockResponsePayload_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *BlockResponsePayload) GetBlocks() *Blocks {
	if x, ok := m.GetResponse().(*BlockResponsePayload_Blocks); ok {
		return x.Blocks
	}
	return nil
}

func (m *BlockResponsePayload) GetErrorCode() *Error {
	if x, ok := m.GetResponse().(*BlockResponsePayload_ErrorCode); ok {
		return x.ErrorCode
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BlockResponsePayload) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BlockResponsePayload_Blocks)(nil),
		(*BlockResponsePayload_ErrorCode)(nil),
	}
}

type Error struct {
	Code                 Error_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Error_ErrorCode" json:"code,omitempty"`
	Desc                 string          `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() Error_ErrorCode {
	if m != nil {
		return m.Code
	}
	return Error_NOT_FOUND
}

func (m *Error) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type QuorumCertificate struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SignatureAggregate   []byte       `protobuf:"bytes,2,opt,name=signatureAggregate,proto3" json:"signatureAggregate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QuorumCertificate) Reset()         { *m = QuorumCertificate{} }
func (m *QuorumCertificate) String() string { return proto.CompactTextString(m) }
func (*QuorumCertificate) ProtoMessage()    {}
func (*QuorumCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *QuorumCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuorumCertificate.Unmarshal(m, b)
}
func (m *QuorumCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuorumCertificate.Marshal(b, m, deterministic)
}
func (m *QuorumCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuorumCertificate.Merge(m, src)
}
func (m *QuorumCertificate) XXX_Size() int {
	return xxx_messageInfo_QuorumCertificate.Size(m)
}
func (m *QuorumCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_QuorumCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_QuorumCertificate proto.InternalMessageInfo

func (m *QuorumCertificate) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QuorumCertificate) GetSignatureAggregate() []byte {
	if m != nil {
		return m.SignatureAggregate
	}
	return nil
}

type Block struct {
	Header               *BlockHeader       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Cert                 *QuorumCertificate `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	Data                 *BlockData         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Txs                  []*Transaction     `protobuf:"bytes,4,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetCert() *QuorumCertificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *Block) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetTxs() []*Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Blocks struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blocks) Reset()         { *m = Blocks{} }
func (m *Blocks) String() string { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()    {}
func (*Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blocks.Unmarshal(m, b)
}
func (m *Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blocks.Marshal(b, m, deterministic)
}
func (m *Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blocks.Merge(m, src)
}
func (m *Blocks) XXX_Size() int {
	return xxx_messageInfo_Blocks.Size(m)
}
func (m *Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_Blocks proto.InternalMessageInfo

func (m *Blocks) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type BlockHeader struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           []byte   `protobuf:"bytes,2,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	QcHash               []byte   `protobuf:"bytes,3,opt,name=qcHash,proto3" json:"qcHash,omitempty"`
	DataHash             []byte   `protobuf:"bytes,4,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	TxHash               []byte   `protobuf:"bytes,5,opt,name=txHash,proto3" json:"txHash,omitempty"`
	StateHash            []byte   `protobuf:"bytes,6,opt,name=stateHash,proto3" json:"stateHash,omitempty"`
	Height               int32    `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetQcHash() []byte {
	if m != nil {
		return m.QcHash
	}
	return nil
}

func (m *BlockHeader) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *BlockHeader) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *BlockHeader) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *BlockHeader) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockData) Reset()         { *m = BlockData{} }
func (m *BlockData) String() string { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()    {}
func (*BlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *BlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockData.Unmarshal(m, b)
}
func (m *BlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockData.Marshal(b, m, deterministic)
}
func (m *BlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockData.Merge(m, src)
}
func (m *BlockData) XXX_Size() int {
	return xxx_messageInfo_BlockData.Size(m)
}
func (m *BlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockData proto.InternalMessageInfo

func (m *BlockData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transaction struct {
	Type                 Transaction_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Transaction_Type" json:"type,omitempty"`
	To                   []byte           `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Nonce                uint64           `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Value                int64            `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Fee                  int64            `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Signature            []byte           `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Data                 []byte           `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_PAYMENT
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Transaction) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Account struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterEnum("Error_ErrorCode", Error_ErrorCode_name, Error_ErrorCode_value)
	proto.RegisterEnum("Transaction_Type", Transaction_Type_name, Transaction_Type_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*HelloPayload)(nil), "HelloPayload")
	proto.RegisterType((*EpochStartPayload)(nil), "EpochStartPayload")
	proto.RegisterType((*ProposalPayload)(nil), "ProposalPayload")
	proto.RegisterType((*VotePayload)(nil), "VotePayload")
	proto.RegisterType((*BlockRequestPayload)(nil), "BlockRequestPayload")
	proto.RegisterType((*BlockResponsePayload)(nil), "BlockResponsePayload")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*QuorumCertificate)(nil), "QuorumCertificate")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*Blocks)(nil), "Blocks")
	proto.RegisterType((*BlockHeader)(nil), "BlockHeader")
	proto.RegisterType((*BlockData)(nil), "BlockData")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*Account)(nil), "Account")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 921 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x25, 0xea, 0x6f, 0x24, 0x3b, 0xf4, 0xd6, 0x28, 0xd4, 0x20, 0x70, 0x6d, 0x22, 0x35,
	0x04, 0xb4, 0x60, 0x00, 0x17, 0x3d, 0x00, 0x25, 0xab, 0x65, 0x50, 0x45, 0x54, 0x96, 0x4a, 0x80,
	0xf6, 0xc5, 0x58, 0x51, 0x6b, 0x8a, 0xa8, 0xc4, 0x65, 0xc8, 0x65, 0x10, 0x1d, 0xa4, 0x37, 0xe9,
	0x5d, 0xfa, 0xdc, 0x73, 0xf4, 0xa5, 0xd8, 0x1f, 0xd2, 0xb4, 0xe3, 0xc2, 0x7d, 0xe8, 0x8b, 0xc4,
	0xf9, 0x66, 0x76, 0xe6, 0x9b, 0x6f, 0x67, 0x77, 0xe1, 0x68, 0x4f, 0xf3, 0x9c, 0x44, 0xd4, 0x49,
	0x33, 0xc6, 0xd9, 0xf3, 0xaf, 0x22, 0xc6, 0xa2, 0x1d, 0x7d, 0x25, 0xad, 0x75, 0x71, 0xfb, 0x8a,
	0x24, 0x07, 0xe5, 0xb2, 0xff, 0x36, 0xa0, 0xfb, 0x46, 0x05, 0xa3, 0x31, 0x98, 0xfc, 0x90, 0xd2,
	0x91, 0x71, 0x6e, 0x8c, 0x8f, 0xaf, 0x4e, 0x1d, 0x8d, 0x97, 0xff, 0xab, 0x43, 0x4a, 0xb1, 0x8c,
	0x40, 0x0e, 0x74, 0x53, 0x72, 0xd8, 0x31, 0xb2, 0x19, 0xb5, 0xce, 0x8d, 0xf1, 0xe0, 0xea, 0xd4,
	0x51, 0x25, 0x9c, 0xb2, 0x84, 0xe3, 0x26, 0x07, 0x5c, 0x06, 0xd9, 0xbf, 0x1b, 0x30, 0xa8, 0x65,
	0x41, 0x27, 0x70, 0xe4, 0xcd, 0xe6, 0x73, 0xff, 0x06, 0xcf, 0xde, 0xbe, 0x9b, 0x05, 0x2b, 0xab,
	0x81, 0x10, 0x1c, 0x97, 0x50, 0xb0, 0xf4, 0x17, 0xc1, 0xcc, 0x32, 0xd0, 0x33, 0x18, 0xcc, 0x96,
	0xfe, 0xd4, 0xbb, 0x09, 0x56, 0x2e, 0x5e, 0x59, 0x4d, 0xd4, 0x03, 0xf3, 0xbd, 0xbf, 0x9a, 0x59,
	0x2d, 0x34, 0x84, 0xde, 0x12, 0xfb, 0x4b, 0x3f, 0x70, 0xe7, 0x96, 0x29, 0xf2, 0x4d, 0xe6, 0xfe,
	0xf4, 0xe7, 0x2a, 0x5f, 0x5b, 0xe4, 0x2b, 0x21, 0x9d, 0xaf, 0x23, 0xf2, 0xad, 0xb0, 0xbb, 0x08,
	0xdc, 0xe9, 0xea, 0xb5, 0xbf, 0xb0, 0xba, 0xf6, 0x06, 0x86, 0x1e, 0xdd, 0xed, 0xd8, 0x52, 0xf1,
	0x44, 0x23, 0xe8, 0x7e, 0xa4, 0x59, 0x1e, 0xb3, 0x44, 0x8a, 0xd0, 0xc6, 0xa5, 0x89, 0x2e, 0xe1,
	0x98, 0xb3, 0x74, 0xb2, 0x63, 0xe1, 0x6f, 0x1e, 0x8d, 0xa3, 0x2d, 0x1f, 0x35, 0x65, 0xc0, 0x03,
	0x14, 0x21, 0x30, 0x79, 0xbc, 0xa7, 0x52, 0x96, 0x16, 0x96, 0xdf, 0xf6, 0x1f, 0x06, 0x9c, 0xcc,
	0x52, 0x16, 0x6e, 0x03, 0x4e, 0x32, 0x5e, 0xd6, 0x1a, 0x83, 0x19, 0xd2, 0x8c, 0xcb, 0x42, 0x83,
	0x2b, 0xe4, 0xbc, 0x2d, 0x58, 0x56, 0xec, 0xa7, 0x34, 0xe3, 0xf1, 0x6d, 0x1c, 0x12, 0x4e, 0xbd,
	0x06, 0x96, 0x11, 0xe8, 0x3b, 0xb0, 0x22, 0x9a, 0xd0, 0x3c, 0xce, 0x83, 0x38, 0x4a, 0x08, 0x2f,
	0x32, 0x2a, 0xab, 0x0f, 0xbd, 0x06, 0xfe, 0xcc, 0x83, 0x5e, 0x40, 0x3f, 0xaf, 0xc2, 0x04, 0x8d,
	0x21, 0xbe, 0x03, 0xd0, 0x05, 0x0c, 0xa9, 0xa0, 0x72, 0x93, 0x14, 0xfb, 0x35, 0xcd, 0x46, 0xa6,
	0xec, 0x62, 0x20, 0xb1, 0x85, 0x84, 0x26, 0x1d, 0x30, 0xd7, 0x6c, 0x73, 0xb0, 0x0b, 0x78, 0xb6,
	0xcc, 0x58, 0xca, 0x72, 0xb2, 0x2b, 0x39, 0x5f, 0x3e, 0xc5, 0x59, 0x33, 0xbe, 0xc7, 0xa1, 0xf9,
	0x90, 0xc3, 0x0b, 0x68, 0xaf, 0x85, 0x64, 0x7a, 0x76, 0x3a, 0x8e, 0x14, 0x10, 0x2b, 0xd0, 0x3e,
	0xc0, 0xe0, 0x3d, 0xe3, 0xf4, 0xff, 0x2d, 0xf9, 0x12, 0x3a, 0x5b, 0x4a, 0x36, 0x34, 0xd3, 0x35,
	0x87, 0x8e, 0xde, 0x34, 0x81, 0x61, 0xed, 0xb3, 0x5d, 0xf8, 0x42, 0x51, 0xa1, 0x1f, 0x0a, 0x9a,
	0x57, 0x3b, 0x85, 0xc0, 0xdc, 0x92, 0x7c, 0x2b, 0x29, 0x0c, 0xb1, 0xfc, 0x46, 0x5f, 0x8a, 0x84,
	0xb5, 0x39, 0xd0, 0x96, 0xbd, 0x87, 0x53, 0x9d, 0x22, 0x4f, 0x59, 0x92, 0x57, 0x6d, 0x5c, 0x40,
	0x47, 0xb6, 0x97, 0xeb, 0x46, 0xba, 0x8a, 0x40, 0xee, 0x35, 0xb0, 0x76, 0xa0, 0x4b, 0xe8, 0xd3,
	0x2c, 0x63, 0xd9, 0x94, 0x6d, 0x54, 0x07, 0x42, 0x9a, 0x99, 0x40, 0xbc, 0x06, 0xbe, 0x73, 0x4d,
	0x00, 0x7a, 0x99, 0xce, 0x6e, 0x27, 0xd0, 0x96, 0x11, 0xe8, 0x25, 0x98, 0xa1, 0x58, 0xa7, 0xce,
	0xae, 0xa5, 0xd6, 0xa9, 0x5f, 0xb1, 0x08, 0x4b, 0xaf, 0xe8, 0x64, 0x43, 0xf3, 0x50, 0x66, 0xef,
	0x63, 0xf9, 0x6d, 0x7f, 0x0b, 0xfd, 0x2a, 0x0c, 0x1d, 0x41, 0x7f, 0xe1, 0xaf, 0x6e, 0x7e, 0xf4,
	0xdf, 0x2d, 0xae, 0xad, 0x86, 0x38, 0x30, 0x13, 0xf7, 0xba, 0x3a, 0x55, 0x86, 0x1d, 0xc3, 0xc9,
	0x67, 0x1b, 0x50, 0x13, 0xd7, 0xf8, 0x77, 0x71, 0x91, 0x03, 0xa8, 0xda, 0x0f, 0x37, 0x8a, 0x32,
	0x1a, 0x11, 0x5e, 0xee, 0xd4, 0x23, 0x1e, 0x71, 0x67, 0xb4, 0x65, 0x9e, 0xff, 0x98, 0xbf, 0x1c,
	0x94, 0xe6, 0x13, 0x83, 0x72, 0x06, 0xe6, 0x86, 0x70, 0xa2, 0x07, 0x01, 0x54, 0xae, 0x6b, 0xc2,
	0x09, 0x96, 0x38, 0x3a, 0x83, 0x16, 0xff, 0x94, 0x8f, 0xcc, 0xf3, 0x96, 0x2c, 0xb5, 0xca, 0x48,
	0x92, 0x93, 0x90, 0xc7, 0x2c, 0xc1, 0xc2, 0x61, 0x8f, 0xa1, 0xa3, 0xb6, 0x0e, 0x9d, 0xd5, 0xf6,
	0xb4, 0x55, 0x1b, 0x64, 0x8d, 0xda, 0x7f, 0x19, 0x30, 0xa8, 0x31, 0x7d, 0x74, 0x8e, 0xce, 0x00,
	0x52, 0x92, 0xd1, 0x84, 0x7b, 0xc2, 0xa3, 0xd4, 0xa8, 0x21, 0x62, 0xce, 0x3e, 0x84, 0xd2, 0xa7,
	0x8e, 0xb2, 0xb6, 0xd0, 0x73, 0xe8, 0x09, 0xb6, 0xd2, 0x63, 0x4a, 0x4f, 0x65, 0x8b, 0x35, 0xfc,
	0x93, 0xf4, 0xb4, 0xd5, 0x1a, 0x65, 0xc9, 0x23, 0xc2, 0xc5, 0xc5, 0x22, 0x5c, 0x1d, 0x7d, 0x44,
	0x4a, 0xa0, 0x36, 0xd1, 0xdd, 0xfa, 0x44, 0x8b, 0x55, 0xe2, 0x16, 0xcb, 0x39, 0xd9, 0xa7, 0xa3,
	0x9e, 0xbc, 0xd6, 0xee, 0x00, 0xfb, 0x6b, 0xe8, 0x57, 0x02, 0xca, 0xf1, 0x12, 0xd2, 0xea, 0x06,
	0xc5, 0xb7, 0xfd, 0xa7, 0x01, 0x83, 0x9a, 0x86, 0xe8, 0x9b, 0x7b, 0x8f, 0xcc, 0x49, 0x5d, 0x5f,
	0xa7, 0xf6, 0xc2, 0x1c, 0x43, 0x93, 0x33, 0xad, 0x47, 0x93, 0x33, 0x74, 0x0a, 0xed, 0x84, 0x25,
	0xa1, 0xba, 0xd1, 0x4c, 0xac, 0x0c, 0x81, 0x7e, 0x24, 0xbb, 0x82, 0x4a, 0x09, 0x5a, 0x58, 0x19,
	0xc8, 0x82, 0xd6, 0x2d, 0xa5, 0xb2, 0xf9, 0x16, 0x16, 0x9f, 0xf7, 0x2f, 0x87, 0xce, 0xc3, 0xcb,
	0xa1, 0xa4, 0xdd, 0xad, 0xd1, 0xbe, 0x00, 0x53, 0xbe, 0x54, 0x03, 0xe8, 0x2e, 0xdd, 0x5f, 0xde,
	0xcc, 0x16, 0xe2, 0x8d, 0x1a, 0x42, 0x2f, 0x98, 0xbb, 0x81, 0xf7, 0x7a, 0xf1, 0x93, 0x65, 0xd8,
	0x3f, 0x40, 0xd7, 0x0d, 0x43, 0x56, 0x24, 0xfc, 0x8e, 0x9d, 0xf1, 0x28, 0x3b, 0xd5, 0x86, 0x32,
	0x26, 0xe6, 0xaf, 0xcd, 0x74, 0xbd, 0xee, 0xc8, 0x87, 0xf2, 0xfb, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x0c, 0xf5, 0xc2, 0xb7, 0xaa, 0x07, 0x00, 0x00,
}
