// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QuorumCertificateS struct {
	Header               *BlockHeaderS        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SignatureAggregate   *SignatureAggregateS `protobuf:"bytes,2,opt,name=signatureAggregate,proto3" json:"signatureAggregate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QuorumCertificateS) Reset()         { *m = QuorumCertificateS{} }
func (m *QuorumCertificateS) String() string { return proto.CompactTextString(m) }
func (*QuorumCertificateS) ProtoMessage()    {}
func (*QuorumCertificateS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *QuorumCertificateS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuorumCertificateS.Unmarshal(m, b)
}
func (m *QuorumCertificateS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuorumCertificateS.Marshal(b, m, deterministic)
}
func (m *QuorumCertificateS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuorumCertificateS.Merge(m, src)
}
func (m *QuorumCertificateS) XXX_Size() int {
	return xxx_messageInfo_QuorumCertificateS.Size(m)
}
func (m *QuorumCertificateS) XXX_DiscardUnknown() {
	xxx_messageInfo_QuorumCertificateS.DiscardUnknown(m)
}

var xxx_messageInfo_QuorumCertificateS proto.InternalMessageInfo

func (m *QuorumCertificateS) GetHeader() *BlockHeaderS {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QuorumCertificateS) GetSignatureAggregate() *SignatureAggregateS {
	if m != nil {
		return m.SignatureAggregate
	}
	return nil
}

type BlockS struct {
	Header               *BlockHeaderS        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Cert                 *QuorumCertificateS  `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	SignatureAggregate   *SignatureAggregateS `protobuf:"bytes,3,opt,name=signatureAggregate,proto3" json:"signatureAggregate,omitempty"`
	Data                 *BlockDataS          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Txs                  []*TransactionS      `protobuf:"bytes,5,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BlockS) Reset()         { *m = BlockS{} }
func (m *BlockS) String() string { return proto.CompactTextString(m) }
func (*BlockS) ProtoMessage()    {}
func (*BlockS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *BlockS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockS.Unmarshal(m, b)
}
func (m *BlockS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockS.Marshal(b, m, deterministic)
}
func (m *BlockS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockS.Merge(m, src)
}
func (m *BlockS) XXX_Size() int {
	return xxx_messageInfo_BlockS.Size(m)
}
func (m *BlockS) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockS.DiscardUnknown(m)
}

var xxx_messageInfo_BlockS proto.InternalMessageInfo

func (m *BlockS) GetHeader() *BlockHeaderS {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BlockS) GetCert() *QuorumCertificateS {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *BlockS) GetSignatureAggregate() *SignatureAggregateS {
	if m != nil {
		return m.SignatureAggregate
	}
	return nil
}

func (m *BlockS) GetData() *BlockDataS {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BlockS) GetTxs() []*TransactionS {
	if m != nil {
		return m.Txs
	}
	return nil
}

type BlockHeaderS struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           []byte   `protobuf:"bytes,2,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	QcHash               []byte   `protobuf:"bytes,3,opt,name=qcHash,proto3" json:"qcHash,omitempty"`
	DataHash             []byte   `protobuf:"bytes,4,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	TxHash               []byte   `protobuf:"bytes,5,opt,name=txHash,proto3" json:"txHash,omitempty"`
	StateHash            []byte   `protobuf:"bytes,6,opt,name=stateHash,proto3" json:"stateHash,omitempty"`
	Height               int32    `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeaderS) Reset()         { *m = BlockHeaderS{} }
func (m *BlockHeaderS) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderS) ProtoMessage()    {}
func (*BlockHeaderS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *BlockHeaderS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderS.Unmarshal(m, b)
}
func (m *BlockHeaderS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderS.Marshal(b, m, deterministic)
}
func (m *BlockHeaderS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderS.Merge(m, src)
}
func (m *BlockHeaderS) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderS.Size(m)
}
func (m *BlockHeaderS) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderS.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderS proto.InternalMessageInfo

func (m *BlockHeaderS) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeaderS) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeaderS) GetQcHash() []byte {
	if m != nil {
		return m.QcHash
	}
	return nil
}

func (m *BlockHeaderS) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *BlockHeaderS) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *BlockHeaderS) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *BlockHeaderS) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeaderS) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockDataS struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockDataS) Reset()         { *m = BlockDataS{} }
func (m *BlockDataS) String() string { return proto.CompactTextString(m) }
func (*BlockDataS) ProtoMessage()    {}
func (*BlockDataS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *BlockDataS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockDataS.Unmarshal(m, b)
}
func (m *BlockDataS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockDataS.Marshal(b, m, deterministic)
}
func (m *BlockDataS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockDataS.Merge(m, src)
}
func (m *BlockDataS) XXX_Size() int {
	return xxx_messageInfo_BlockDataS.Size(m)
}
func (m *BlockDataS) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockDataS.DiscardUnknown(m)
}

var xxx_messageInfo_BlockDataS proto.InternalMessageInfo

func (m *BlockDataS) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TransactionS struct {
	Type                 int32       `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	To                   []byte      `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	From                 []byte      `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Nonce                uint64      `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Value                int64       `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	Fee                  int64       `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Signature            *SignatureS `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	Hash                 []byte      `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	Data                 []byte      `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransactionS) Reset()         { *m = TransactionS{} }
func (m *TransactionS) String() string { return proto.CompactTextString(m) }
func (*TransactionS) ProtoMessage()    {}
func (*TransactionS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *TransactionS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionS.Unmarshal(m, b)
}
func (m *TransactionS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionS.Marshal(b, m, deterministic)
}
func (m *TransactionS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionS.Merge(m, src)
}
func (m *TransactionS) XXX_Size() int {
	return xxx_messageInfo_TransactionS.Size(m)
}
func (m *TransactionS) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionS.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionS proto.InternalMessageInfo

func (m *TransactionS) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TransactionS) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionS) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransactionS) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionS) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TransactionS) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *TransactionS) GetSignature() *SignatureS {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TransactionS) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TransactionS) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SignatureS struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureS) Reset()         { *m = SignatureS{} }
func (m *SignatureS) String() string { return proto.CompactTextString(m) }
func (*SignatureS) ProtoMessage()    {}
func (*SignatureS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *SignatureS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureS.Unmarshal(m, b)
}
func (m *SignatureS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureS.Marshal(b, m, deterministic)
}
func (m *SignatureS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureS.Merge(m, src)
}
func (m *SignatureS) XXX_Size() int {
	return xxx_messageInfo_SignatureS.Size(m)
}
func (m *SignatureS) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureS.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureS proto.InternalMessageInfo

func (m *SignatureS) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *SignatureS) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SignatureAggregateS struct {
	Bitmap               []byte   `protobuf:"bytes,1,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureAggregateS) Reset()         { *m = SignatureAggregateS{} }
func (m *SignatureAggregateS) String() string { return proto.CompactTextString(m) }
func (*SignatureAggregateS) ProtoMessage()    {}
func (*SignatureAggregateS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}

func (m *SignatureAggregateS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureAggregateS.Unmarshal(m, b)
}
func (m *SignatureAggregateS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureAggregateS.Marshal(b, m, deterministic)
}
func (m *SignatureAggregateS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureAggregateS.Merge(m, src)
}
func (m *SignatureAggregateS) XXX_Size() int {
	return xxx_messageInfo_SignatureAggregateS.Size(m)
}
func (m *SignatureAggregateS) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureAggregateS.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureAggregateS proto.InternalMessageInfo

func (m *SignatureAggregateS) GetBitmap() []byte {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

func (m *SignatureAggregateS) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Account struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Origin               []byte   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Voters               [][]byte `protobuf:"bytes,4,rep,name=voters,proto3" json:"voters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Account) GetOrigin() []byte {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *Account) GetVoters() [][]byte {
	if m != nil {
		return m.Voters
	}
	return nil
}

type Record struct {
	Snap                 []byte   `protobuf:"bytes,1,opt,name=snap,proto3" json:"snap,omitempty"`
	Parent               []byte   `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Siblings             [][]byte `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{8}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetSnap() []byte {
	if m != nil {
		return m.Snap
	}
	return nil
}

func (m *Record) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Record) GetSiblings() [][]byte {
	if m != nil {
		return m.Siblings
	}
	return nil
}

type Snapshot struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Proposer             []byte   `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Entries              []*Entry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{9}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Snapshot) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *Snapshot) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Entry struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Account              []byte   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{10}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Entry) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*QuorumCertificateS)(nil), "QuorumCertificateS")
	proto.RegisterType((*BlockS)(nil), "BlockS")
	proto.RegisterType((*BlockHeaderS)(nil), "BlockHeaderS")
	proto.RegisterType((*BlockDataS)(nil), "BlockDataS")
	proto.RegisterType((*TransactionS)(nil), "TransactionS")
	proto.RegisterType((*SignatureS)(nil), "SignatureS")
	proto.RegisterType((*SignatureAggregateS)(nil), "SignatureAggregateS")
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterType((*Record)(nil), "Record")
	proto.RegisterType((*Snapshot)(nil), "Snapshot")
	proto.RegisterType((*Entry)(nil), "Entry")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x63, 0xc7, 0x49, 0xa7, 0x2d, 0x42, 0xdb, 0xaa, 0xb2, 0xaa, 0x8a, 0x46, 0x96, 0x10,
	0xe5, 0x92, 0x43, 0x39, 0x22, 0x21, 0xb5, 0x14, 0xa9, 0x12, 0x17, 0x58, 0x73, 0x42, 0x5c, 0x36,
	0xce, 0xd4, 0xb1, 0x68, 0x76, 0xcd, 0xee, 0xa4, 0x6a, 0x8f, 0x7c, 0x25, 0x57, 0xc4, 0x97, 0xa0,
	0x1d, 0x6f, 0x1c, 0x4b, 0x0d, 0x02, 0x6e, 0xf3, 0xde, 0xdb, 0x99, 0x9d, 0x37, 0x3b, 0x36, 0xec,
	0x3b, 0x32, 0x56, 0x55, 0x38, 0x6d, 0xac, 0x21, 0x93, 0x7f, 0x8f, 0x40, 0x7c, 0x5c, 0x19, 0xbb,
	0x5a, 0xbe, 0x45, 0x4b, 0xf5, 0x4d, 0x5d, 0x2a, 0xc2, 0x42, 0x3c, 0x87, 0x74, 0x81, 0x6a, 0x8e,
	0x36, 0x8b, 0x26, 0xd1, 0xd9, 0xee, 0xf9, 0xfe, 0xf4, 0xf2, 0xd6, 0x94, 0x5f, 0xaf, 0x99, 0x2b,
	0x64, 0x10, 0xc5, 0x15, 0x08, 0x57, 0x57, 0x5a, 0xd1, 0xca, 0xe2, 0x45, 0x55, 0x59, 0xac, 0x14,
	0x61, 0x36, 0xe0, 0x94, 0xc3, 0x69, 0xf1, 0x48, 0x2a, 0xe4, 0x96, 0xf3, 0xf9, 0xcf, 0x08, 0x52,
	0x2e, 0xff, 0xcf, 0xf7, 0xbe, 0x80, 0xa4, 0x44, 0x4b, 0xe1, 0xa6, 0x83, 0xe9, 0x63, 0x07, 0x92,
	0x0f, 0xfc, 0xa1, 0xc1, 0xf8, 0xff, 0x1a, 0x14, 0xa7, 0x90, 0xcc, 0x15, 0xa9, 0x2c, 0xe1, 0xbc,
	0xdd, 0xb6, 0xa7, 0x2b, 0x45, 0xaa, 0x90, 0x2c, 0x88, 0x53, 0x88, 0xe9, 0xde, 0x65, 0xc3, 0x49,
	0xcc, 0x3d, 0x7f, 0xb2, 0x4a, 0x3b, 0x55, 0x52, 0x6d, 0x74, 0x21, 0xbd, 0x92, 0xff, 0x8a, 0x60,
	0xaf, 0xef, 0x44, 0x08, 0x48, 0x16, 0xca, 0x2d, 0xd8, 0xe6, 0x9e, 0xe4, 0x58, 0x3c, 0x03, 0x68,
	0x94, 0x45, 0x4d, 0xd7, 0x5e, 0x19, 0xb0, 0xd2, 0x63, 0xc4, 0x11, 0xa4, 0xdf, 0x4a, 0xd6, 0x62,
	0xd6, 0x02, 0x12, 0xc7, 0x30, 0xf6, 0x5d, 0xb0, 0x92, 0xb0, 0xd2, 0x61, 0x9f, 0x43, 0xf7, 0xac,
	0x0c, 0xdb, 0x9c, 0x16, 0x89, 0x13, 0xd8, 0x71, 0xa4, 0x08, 0x59, 0x4a, 0x59, 0xda, 0x10, 0x3e,
	0x6b, 0x81, 0x75, 0xb5, 0xa0, 0x6c, 0x34, 0x89, 0xce, 0x86, 0x32, 0x20, 0x9f, 0x45, 0xf5, 0x12,
	0x1d, 0xa9, 0x65, 0x93, 0x8d, 0x27, 0xd1, 0x59, 0x2c, 0x37, 0x44, 0x3e, 0x01, 0xd8, 0x4c, 0xc6,
	0x3b, 0xe4, 0xa1, 0x05, 0x87, 0x3e, 0xce, 0x7f, 0x44, 0xb0, 0xd7, 0x1f, 0x8e, 0x3f, 0x44, 0x0f,
	0x0d, 0xf2, 0xa1, 0xa1, 0xe4, 0x58, 0x3c, 0x81, 0x01, 0x99, 0x60, 0x7f, 0x40, 0xc6, 0x9f, 0xb9,
	0xb1, 0x66, 0x19, 0x4c, 0x73, 0x2c, 0x0e, 0x61, 0xa8, 0x8d, 0x2e, 0x91, 0xfd, 0x26, 0xb2, 0x05,
	0x9e, 0xbd, 0x53, 0xb7, 0x2b, 0x64, 0xaf, 0xb1, 0x6c, 0x81, 0x78, 0x0a, 0xf1, 0x0d, 0x22, 0x9b,
	0x8c, 0xa5, 0x0f, 0xc5, 0x4b, 0xd8, 0xe9, 0x5e, 0x99, 0x1d, 0xfa, 0x47, 0xed, 0x96, 0xa1, 0x90,
	0x1b, 0xb5, 0x7b, 0xa7, 0x71, 0xef, 0x9d, 0xd6, 0xce, 0x76, 0x7a, 0xce, 0xde, 0x00, 0x6c, 0x0a,
	0x74, 0x2d, 0x47, 0xbd, 0x96, 0x4f, 0xfa, 0x97, 0x0e, 0xc2, 0xc4, 0xd7, 0x44, 0xfe, 0x1e, 0x0e,
	0xb6, 0x6c, 0xa3, 0x7f, 0x88, 0x59, 0x4d, 0x4b, 0xd5, 0x84, 0x52, 0x01, 0xfd, 0xa5, 0x18, 0xc2,
	0xe8, 0xa2, 0x2c, 0xcd, 0x4a, 0xd3, 0x66, 0x50, 0xd1, 0xd6, 0x41, 0xb5, 0xa9, 0x61, 0x50, 0x47,
	0x90, 0x1a, 0x5b, 0x57, 0xb5, 0x5e, 0xef, 0x57, 0x8b, 0x3c, 0x7f, 0x67, 0x08, 0xad, 0xcb, 0x92,
	0x49, 0xec, 0xf9, 0x16, 0xe5, 0x1f, 0x20, 0x95, 0x58, 0x1a, 0x3b, 0xf7, 0x7e, 0x9d, 0xee, 0x9a,
	0xe4, 0xd8, 0x67, 0xb5, 0xbb, 0x1b, 0x2e, 0x09, 0xc8, 0x6f, 0xab, 0xab, 0x67, 0xb7, 0xb5, 0xae,
	0x5c, 0x16, 0x73, 0xbd, 0x0e, 0xe7, 0x5f, 0x60, 0x5c, 0x68, 0xd5, 0xb8, 0x85, 0xa1, 0xad, 0x5f,
	0xc8, 0x31, 0x8c, 0x1b, 0x6b, 0x1a, 0xe3, 0xd0, 0x86, 0xaa, 0x1d, 0x16, 0x13, 0x18, 0xa1, 0x26,
	0x5b, 0x63, 0x5b, 0x76, 0xf7, 0x3c, 0x9d, 0xbe, 0xd3, 0x64, 0x1f, 0xe4, 0x9a, 0xce, 0x5f, 0xc3,
	0x90, 0x19, 0x91, 0xc1, 0x48, 0xcd, 0xe7, 0x16, 0x9d, 0x0b, 0xd5, 0xd7, 0x90, 0x95, 0x76, 0x72,
	0xa1, 0xfe, 0x1a, 0x5e, 0x26, 0x9f, 0x07, 0xcd, 0x6c, 0x96, 0xf2, 0x5f, 0xf3, 0xd5, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x59, 0x6e, 0x15, 0x01, 0x46, 0x05, 0x00, 0x00,
}
