// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	blockchain "github.com/gagarinchain/network/blockchain"
	common "github.com/gagarinchain/network/common/eth/common"

	context "context"

	mock "github.com/stretchr/testify/mock"

	networkcommon "github.com/gagarinchain/network/common"
)

// BlockService is an autogenerated mock type for the BlockService type
type BlockService struct {
	mock.Mock
}

// RequestBlock provides a mock function with given fields: ctx, hash, peer
func (_m *BlockService) RequestBlock(ctx context.Context, hash common.Hash, peer *networkcommon.Peer) (chan *blockchain.Block, chan error) {
	ret := _m.Called(ctx, hash, peer)

	var r0 chan *blockchain.Block
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, *networkcommon.Peer) chan *blockchain.Block); ok {
		r0 = rf(ctx, hash, peer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *blockchain.Block)
		}
	}

	var r1 chan error
	if rf, ok := ret.Get(1).(func(context.Context, common.Hash, *networkcommon.Peer) chan error); ok {
		r1 = rf(ctx, hash, peer)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	return r0, r1
}

// RequestBlockHeaderBatch provides a mock function with given fields: ctx, low, high, peer
func (_m *BlockService) RequestBlockHeaderBatch(ctx context.Context, low int32, high int32, peer *networkcommon.Peer) (chan *blockchain.Header, chan error) {
	ret := _m.Called(ctx, low, high, peer)

	var r0 chan *blockchain.Header
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, *networkcommon.Peer) chan *blockchain.Header); ok {
		r0 = rf(ctx, low, high, peer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *blockchain.Header)
		}
	}

	var r1 chan error
	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, *networkcommon.Peer) chan error); ok {
		r1 = rf(ctx, low, high, peer)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	return r0, r1
}

// RequestBlocksAtHeight provides a mock function with given fields: ctx, height, peer
func (_m *BlockService) RequestBlocksAtHeight(ctx context.Context, height int32, peer *networkcommon.Peer) (chan *blockchain.Block, chan error) {
	ret := _m.Called(ctx, height, peer)

	var r0 chan *blockchain.Block
	if rf, ok := ret.Get(0).(func(context.Context, int32, *networkcommon.Peer) chan *blockchain.Block); ok {
		r0 = rf(ctx, height, peer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *blockchain.Block)
		}
	}

	var r1 chan error
	if rf, ok := ret.Get(1).(func(context.Context, int32, *networkcommon.Peer) chan error); ok {
		r1 = rf(ctx, height, peer)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	return r0, r1
}

// RequestFork provides a mock function with given fields: ctx, lowHeight, hash, peer
func (_m *BlockService) RequestFork(ctx context.Context, lowHeight int32, hash common.Hash, peer *networkcommon.Peer) (chan *blockchain.Block, chan error) {
	ret := _m.Called(ctx, lowHeight, hash, peer)

	var r0 chan *blockchain.Block
	if rf, ok := ret.Get(0).(func(context.Context, int32, common.Hash, *networkcommon.Peer) chan *blockchain.Block); ok {
		r0 = rf(ctx, lowHeight, hash, peer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *blockchain.Block)
		}
	}

	var r1 chan error
	if rf, ok := ret.Get(1).(func(context.Context, int32, common.Hash, *networkcommon.Peer) chan error); ok {
		r1 = rf(ctx, lowHeight, hash, peer)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	return r0, r1
}
