// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CurrentViewGetter is an autogenerated mock type for the CurrentViewGetter type
type CurrentViewGetter struct {
	mock.Mock
}

// GetCurrentView provides a mock function with given fields:
func (_m *CurrentViewGetter) getCurrentView() int32 {
	ret := _m.Called()

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}
