// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import common "github.com/gagarinchain/network/common"
import context "context"
import mock "github.com/stretchr/testify/mock"

// EventBus is an autogenerated mock type for the EventBus type
type EventBus struct {
	mock.Mock
}

// FireEvent provides a mock function with given fields: event
func (_m *EventBus) FireEvent(event *common.Event) {
	_m.Called(event)
}

// Run provides a mock function with given fields: ctx
func (_m *EventBus) Run(ctx context.Context) {
	_m.Called(ctx)
}
