// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import hotstuff "github.com/poslibp2p/hotstuff"
import mock "github.com/stretchr/testify/mock"

// EventNotifier is an autogenerated mock type for the EventNotifier type
type EventNotifier struct {
	mock.Mock
}

// SubscribeProtocolEvents provides a mock function with given fields: _a0
func (_m *EventNotifier) SubscribeProtocolEvents(_a0 chan hotstuff.Event) {
	_m.Called(_a0)
}
