// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import hotstuff "github.com/gagarinchain/network/hotstuff"
import mock "github.com/stretchr/testify/mock"

// EventNotifier is an autogenerated mock type for the EventNotifier type
type EventNotifier struct {
	mock.Mock
}

// FireEvent provides a mock function with given fields: event
func (_m *EventNotifier) FireEvent(event hotstuff.Event) {
	_m.Called(event)
}

// SubscribeProtocolEvents provides a mock function with given fields: sub
func (_m *EventNotifier) SubscribeProtocolEvents(sub chan hotstuff.Event) {
	_m.Called(sub)
}
