// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import message "github.com/poslibp2p/common/message"
import mock "github.com/stretchr/testify/mock"

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0
func (_m *Handler) Handle(_a0 *message.Message) {
	_m.Called(_a0)
}
