// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import blockchain "github.com/gagarinchain/network/blockchain"

import mock "github.com/stretchr/testify/mock"

// HQCHandler is an autogenerated mock type for the HQCHandler type
type HQCHandler struct {
	mock.Mock
}

// HQC provides a mock function with given fields:
func (_m *HQCHandler) HQC() *blockchain.QuorumCertificate {
	ret := _m.Called()

	var r0 *blockchain.QuorumCertificate
	if rf, ok := ret.Get(0).(func() *blockchain.QuorumCertificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blockchain.QuorumCertificate)
		}
	}

	return r0
}

// Update provides a mock function with given fields: qc
func (_m *HQCHandler) Update(qc *blockchain.QuorumCertificate) {
	_m.Called(qc)
}
