// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isBlockResponsePayload_Response is an autogenerated mock type for the isBlockResponsePayload_Response type
type isBlockResponsePayload_Response struct {
	mock.Mock
}

// isBlockResponsePayload_Response provides a mock function with given fields:
func (_m *isBlockResponsePayload_Response) isBlockResponsePayload_Response() {
	_m.Called()
}
