// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isEpochStartPayload_Body is an autogenerated mock type for the isEpochStartPayload_Body type
type isEpochStartPayload_Body struct {
	mock.Mock
}

// isEpochStartPayload_Body provides a mock function with given fields:
func (_m *isEpochStartPayload_Body) isEpochStartPayload_Body() {
	_m.Called()
}
