// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isHeadersResponse_Response is an autogenerated mock type for the isHeadersResponse_Response type
type isHeadersResponse_Response struct {
	mock.Mock
}

// isHeadersResponse_Response provides a mock function with given fields:
func (_m *isHeadersResponse_Response) isHeadersResponse_Response() {
	_m.Called()
}
