// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import tx "github.com/poslibp2p/common/tx"

// Iterator is an autogenerated mock type for the Iterator type
type Iterator struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *Iterator) Next() *tx.Transaction {
	ret := _m.Called()

	var r0 *tx.Transaction
	if rf, ok := ret.Get(0).(func() *tx.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx.Transaction)
		}
	}

	return r0
}
