// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/gagarinchain/network/common/api"
import mock "github.com/stretchr/testify/mock"

// OnNextView is an autogenerated mock type for the OnNextView type
type OnNextView struct {
	mock.Mock
}

// OnNewView provides a mock function with given fields: pacer, bc, newView
func (_m *OnNextView) OnNewView(pacer api.Pacer, bc api.Blockchain, newView int32) {
	_m.Called(pacer, bc, newView)
}
