// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/gagarinchain/network/common/api"
import mock "github.com/stretchr/testify/mock"

// OnProposal is an autogenerated mock type for the OnProposal type
type OnProposal struct {
	mock.Mock
}

// CreateBlock provides a mock function with given fields: pacer, bc
func (_m *OnProposal) CreateBlock(pacer api.Pacer, bc api.Blockchain) api.Block {
	ret := _m.Called(pacer, bc)

	var r0 api.Block
	if rf, ok := ret.Get(0).(func(api.Pacer, api.Blockchain) api.Block); ok {
		r0 = rf(pacer, bc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Block)
		}
	}

	return r0
}
