// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/gagarinchain/network/common/api"
import mock "github.com/stretchr/testify/mock"

// OnReceiveProposal is an autogenerated mock type for the OnReceiveProposal type
type OnReceiveProposal struct {
	mock.Mock
}

// AfterProposedBlockAdded provides a mock function with given fields: pacer, bc, proposal
func (_m *OnReceiveProposal) AfterProposedBlockAdded(pacer api.Pacer, bc api.Blockchain, proposal api.Proposal) {
	_m.Called(pacer, bc, proposal)
}

// AfterVoted provides a mock function with given fields: pacer, bc, vote
func (_m *OnReceiveProposal) AfterVoted(pacer api.Pacer, bc api.Blockchain, vote api.Vote) {
	_m.Called(pacer, bc, vote)
}

// BeforeProposedBlockAdded provides a mock function with given fields: pacer, bc, proposal
func (_m *OnReceiveProposal) BeforeProposedBlockAdded(pacer api.Pacer, bc api.Blockchain, proposal api.Proposal) {
	_m.Called(pacer, bc, proposal)
}

// BeforeVoted provides a mock function with given fields: pacer, bc, vote
func (_m *OnReceiveProposal) BeforeVoted(pacer api.Pacer, bc api.Blockchain, vote api.Vote) {
	_m.Called(pacer, bc, vote)
}
