// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/gagarinchain/network/common/api"
import mock "github.com/stretchr/testify/mock"

// OnVoteReceived is an autogenerated mock type for the OnVoteReceived type
type OnVoteReceived struct {
	mock.Mock
}

// OnQCFinished provides a mock function with given fields: pacer, bc, qc
func (_m *OnVoteReceived) OnQCFinished(pacer api.Pacer, bc api.Blockchain, qc api.QuorumCertificate) {
	_m.Called(pacer, bc, qc)
}

// OnVoteReceived provides a mock function with given fields: pacer, bc, vote
func (_m *OnVoteReceived) OnVoteReceived(pacer api.Pacer, bc api.Blockchain, vote api.Vote) {
	_m.Called(pacer, bc, vote)
}
