// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gagarinchain "github.com/gagarinchain/network"
import mock "github.com/stretchr/testify/mock"

// Persistable is an autogenerated mock type for the Persistable type
type Persistable struct {
	mock.Mock
}

// Persist provides a mock function with given fields: storage
func (_m *Persistable) Persist(storage gagarinchain.Storage) error {
	ret := _m.Called(storage)

	var r0 error
	if rf, ok := ret.Get(0).(func(gagarinchain.Storage) error); ok {
		r0 = rf(storage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
