// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import big "math/big"
import common "github.com/gagarinchain/network/common/eth/common"
import crypto "github.com/gagarinchain/network/common/eth/crypto"
import mock "github.com/stretchr/testify/mock"
import networkcommon "github.com/gagarinchain/network/common"

// ProposerForHeight is an autogenerated mock type for the ProposerForHeight type
type ProposerForHeight struct {
	mock.Mock
}

// GetBitmap provides a mock function with given fields: src
func (_m *ProposerForHeight) GetBitmap(src map[common.Address]*crypto.Signature) (*big.Int, int) {
	ret := _m.Called(src)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(map[common.Address]*crypto.Signature) *big.Int); ok {
		r0 = rf(src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(map[common.Address]*crypto.Signature) int); ok {
		r1 = rf(src)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// ProposerForHeight provides a mock function with given fields: blockHeight
func (_m *ProposerForHeight) ProposerForHeight(blockHeight int32) *networkcommon.Peer {
	ret := _m.Called(blockHeight)

	var r0 *networkcommon.Peer
	if rf, ok := ret.Get(0).(func(int32) *networkcommon.Peer); ok {
		r0 = rf(blockHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*networkcommon.Peer)
		}
	}

	return r0
}
