// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import common "github.com/gagarinchain/network/common"
import mock "github.com/stretchr/testify/mock"

// ProposerForHeight is an autogenerated mock type for the ProposerForHeight type
type ProposerForHeight struct {
	mock.Mock
}

// ProposerForHeight provides a mock function with given fields: blockHeight
func (_m *ProposerForHeight) ProposerForHeight(blockHeight int32) *common.Peer {
	ret := _m.Called(blockHeight)

	var r0 *common.Peer
	if rf, ok := ret.Get(0).(func(int32) *common.Peer); ok {
		r0 = rf(blockHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.Peer)
		}
	}

	return r0
}
