// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/gagarinchain/common/api"
import common "github.com/gagarinchain/common/eth/common"
import crypto "github.com/gagarinchain/common/eth/crypto"
import mock "github.com/stretchr/testify/mock"
import pb "github.com/gagarinchain/common/protobuff"

// QuorumCertificate is an autogenerated mock type for the QuorumCertificate type
type QuorumCertificate struct {
	mock.Mock
}

// GetHash provides a mock function with given fields:
func (_m *QuorumCertificate) GetHash() common.Hash {
	ret := _m.Called()

	var r0 common.Hash
	if rf, ok := ret.Get(0).(func() common.Hash); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	return r0
}

// GetMessage provides a mock function with given fields:
func (_m *QuorumCertificate) GetMessage() *pb.QuorumCertificate {
	ret := _m.Called()

	var r0 *pb.QuorumCertificate
	if rf, ok := ret.Get(0).(func() *pb.QuorumCertificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.QuorumCertificate)
		}
	}

	return r0
}

// IsValid provides a mock function with given fields: qcHash, committee
func (_m *QuorumCertificate) IsValid(qcHash common.Hash, committee []*crypto.PublicKey) (bool, error) {
	ret := _m.Called(qcHash, committee)

	var r0 bool
	if rf, ok := ret.Get(0).(func(common.Hash, []*crypto.PublicKey) bool); ok {
		r0 = rf(qcHash, committee)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(common.Hash, []*crypto.PublicKey) error); ok {
		r1 = rf(qcHash, committee)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QrefBlock provides a mock function with given fields:
func (_m *QuorumCertificate) QrefBlock() api.Header {
	ret := _m.Called()

	var r0 api.Header
	if rf, ok := ret.Get(0).(func() api.Header); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Header)
		}
	}

	return r0
}

// SignatureAggregate provides a mock function with given fields:
func (_m *QuorumCertificate) SignatureAggregate() *crypto.SignatureAggregate {
	ret := _m.Called()

	var r0 *crypto.SignatureAggregate
	if rf, ok := ret.Get(0).(func() *crypto.SignatureAggregate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crypto.SignatureAggregate)
		}
	}

	return r0
}

// ToStorageProto provides a mock function with given fields:
func (_m *QuorumCertificate) ToStorageProto() *pb.QuorumCertificateS {
	ret := _m.Called()

	var r0 *pb.QuorumCertificateS
	if rf, ok := ret.Get(0).(func() *pb.QuorumCertificateS); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.QuorumCertificateS)
		}
	}

	return r0
}
