// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import message "github.com/poslibp2p/message"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: msg
func (_m *Service) Broadcast(msg *message.Message) {
	_m.Called(msg)
}

// SendMessage provides a mock function with given fields: peer, msg
func (_m *Service) SendMessage(peer *message.Peer, msg *message.Message) {
	_m.Called(peer, msg)
}

// SendMessageToRandomPeer provides a mock function with given fields: req
func (_m *Service) SendMessageToRandomPeer(req *message.Message) *message.Message {
	ret := _m.Called(req)

	var r0 *message.Message
	if rf, ok := ret.Get(0).(func(*message.Message) *message.Message); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*message.Message)
		}
	}

	return r0
}

// SendMessageTriggered provides a mock function with given fields: peer, msg, trigger
func (_m *Service) SendMessageTriggered(peer *message.Peer, msg *message.Message, trigger chan interface{}) {
	_m.Called(peer, msg, trigger)
}
