// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Slashing is an autogenerated mock type for the Slashing type
type Slashing struct {
	mock.Mock
}
