// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import common "github.com/poslibp2p/eth/common"
import context "context"
import mock "github.com/stretchr/testify/mock"

// Synchronizer is an autogenerated mock type for the Synchronizer type
type Synchronizer struct {
	mock.Mock
}

// RequestBlocks provides a mock function with given fields: ctx, low, high
func (_m *Synchronizer) RequestBlocks(ctx context.Context, low int32, high int32) {
	_m.Called(ctx, low, high)
}

// RequestFork provides a mock function with given fields: ctx, hash
func (_m *Synchronizer) RequestFork(ctx context.Context, hash common.Hash) error {
	ret := _m.Called(ctx, hash)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) error); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
