// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import blockchain "github.com/poslibp2p/blockchain"
import common "github.com/poslibp2p/eth/common"
import mock "github.com/stretchr/testify/mock"

// Synchronizer is an autogenerated mock type for the Synchronizer type
type Synchronizer struct {
	mock.Mock
}

// Bootstrap provides a mock function with given fields:
func (_m *Synchronizer) Bootstrap() {
	_m.Called()
}

// RequestBlockSynchronously provides a mock function with given fields: hash
func (_m *Synchronizer) RequestBlock(hash common.Hash) {
	_m.Called(hash)
}

// RequestBlockWithDeps provides a mock function with given fields: header
func (_m *Synchronizer) RequestBlockWithDeps(header *blockchain.Header) {
	_m.Called(header)
}
