// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/gagarinchain/common/api"

	mock "github.com/stretchr/testify/mock"
)

// TransactionPool is an autogenerated mock type for the TransactionPool type
type TransactionPool struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *TransactionPool) Add(_a0 api.Transaction) {
	_m.Called(_a0)
}

// Drain provides a mock function with given fields: ctx
func (_m *TransactionPool) Drain(ctx context.Context) chan []api.Transaction {
	ret := _m.Called(ctx)

	var r0 chan []api.Transaction
	if rf, ok := ret.Get(0).(func(context.Context) chan []api.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan []api.Transaction)
		}
	}

	return r0
}

// Iterator provides a mock function with given fields:
func (_m *TransactionPool) Iterator() api.Iterator {
	ret := _m.Called()

	var r0 api.Iterator
	if rf, ok := ret.Get(0).(func() api.Iterator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Iterator)
		}
	}

	return r0
}

// Remove provides a mock function with given fields: transaction
func (_m *TransactionPool) Remove(transaction api.Transaction) {
	_m.Called(transaction)
}

// RemoveAll provides a mock function with given fields: transactions
func (_m *TransactionPool) RemoveAll(transactions ...api.Transaction) {
	_va := make([]interface{}, len(transactions))
	for _i := range transactions {
		_va[_i] = transactions[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
