// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_HELLO          Message_MessageType = 0
	Message_VOTE           Message_MessageType = 1
	Message_PROPOSAL       Message_MessageType = 2
	Message_BLOCK_REQUEST  Message_MessageType = 3
	Message_BLOCK_RESPONSE Message_MessageType = 4
)

var Message_MessageType_name = map[int32]string{
	0: "HELLO",
	1: "VOTE",
	2: "PROPOSAL",
	3: "BLOCK_REQUEST",
	4: "BLOCK_RESPONSE",
}

var Message_MessageType_value = map[string]int32{
	"HELLO":          0,
	"VOTE":           1,
	"PROPOSAL":       2,
	"BLOCK_REQUEST":  3,
	"BLOCK_RESPONSE": 4,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Error_ErrorCode int32

const (
	Error_NO_FOUND    Error_ErrorCode = 0
	Error_BAD_REQUEST Error_ErrorCode = 1
)

var Error_ErrorCode_name = map[int32]string{
	0: "NO_FOUND",
	1: "BAD_REQUEST",
}

var Error_ErrorCode_value = map[string]int32{
	"NO_FOUND":    0,
	"BAD_REQUEST": 1,
}

func (x Error_ErrorCode) String() string {
	return proto.EnumName(Error_ErrorCode_name, int32(x))
}

func (Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5, 0}
}

type Message struct {
	Type                 Message_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=Message_MessageType" json:"type,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload              *any.Any            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_MessageType {
	if m != nil {
		return m.Type
	}
	return Message_HELLO
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HelloPayload struct {
	HelloMessage         string   `protobuf:"bytes,1,opt,name=helloMessage,proto3" json:"helloMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloPayload) Reset()         { *m = HelloPayload{} }
func (m *HelloPayload) String() string { return proto.CompactTextString(m) }
func (*HelloPayload) ProtoMessage()    {}
func (*HelloPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *HelloPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloPayload.Unmarshal(m, b)
}
func (m *HelloPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloPayload.Marshal(b, m, deterministic)
}
func (m *HelloPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloPayload.Merge(m, src)
}
func (m *HelloPayload) XXX_Size() int {
	return xxx_messageInfo_HelloPayload.Size(m)
}
func (m *HelloPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloPayload.DiscardUnknown(m)
}

var xxx_messageInfo_HelloPayload proto.InternalMessageInfo

func (m *HelloPayload) GetHelloMessage() string {
	if m != nil {
		return m.HelloMessage
	}
	return ""
}

type ProposalPayload struct {
	Cert                 *QuorumCertificate `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Block                *Block             `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProposalPayload) Reset()         { *m = ProposalPayload{} }
func (m *ProposalPayload) String() string { return proto.CompactTextString(m) }
func (*ProposalPayload) ProtoMessage()    {}
func (*ProposalPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ProposalPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalPayload.Unmarshal(m, b)
}
func (m *ProposalPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalPayload.Marshal(b, m, deterministic)
}
func (m *ProposalPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalPayload.Merge(m, src)
}
func (m *ProposalPayload) XXX_Size() int {
	return xxx_messageInfo_ProposalPayload.Size(m)
}
func (m *ProposalPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalPayload proto.InternalMessageInfo

func (m *ProposalPayload) GetCert() *QuorumCertificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *ProposalPayload) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type BlockRequestPayload struct {
	//TODO Think about using oneof here
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequestPayload) Reset()         { *m = BlockRequestPayload{} }
func (m *BlockRequestPayload) String() string { return proto.CompactTextString(m) }
func (*BlockRequestPayload) ProtoMessage()    {}
func (*BlockRequestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *BlockRequestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequestPayload.Unmarshal(m, b)
}
func (m *BlockRequestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequestPayload.Marshal(b, m, deterministic)
}
func (m *BlockRequestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequestPayload.Merge(m, src)
}
func (m *BlockRequestPayload) XXX_Size() int {
	return xxx_messageInfo_BlockRequestPayload.Size(m)
}
func (m *BlockRequestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequestPayload proto.InternalMessageInfo

func (m *BlockRequestPayload) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockRequestPayload) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockResponsePayload struct {
	// Types that are valid to be assigned to Response:
	//	*BlockResponsePayload_Block
	//	*BlockResponsePayload_ErrorCode
	Response             isBlockResponsePayload_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *BlockResponsePayload) Reset()         { *m = BlockResponsePayload{} }
func (m *BlockResponsePayload) String() string { return proto.CompactTextString(m) }
func (*BlockResponsePayload) ProtoMessage()    {}
func (*BlockResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *BlockResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponsePayload.Unmarshal(m, b)
}
func (m *BlockResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponsePayload.Marshal(b, m, deterministic)
}
func (m *BlockResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponsePayload.Merge(m, src)
}
func (m *BlockResponsePayload) XXX_Size() int {
	return xxx_messageInfo_BlockResponsePayload.Size(m)
}
func (m *BlockResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponsePayload proto.InternalMessageInfo

type isBlockResponsePayload_Response interface {
	isBlockResponsePayload_Response()
}

type BlockResponsePayload_Block struct {
	Block *Block `protobuf:"bytes,1,opt,name=block,proto3,oneof"`
}

type BlockResponsePayload_ErrorCode struct {
	ErrorCode *Error `protobuf:"bytes,2,opt,name=errorCode,proto3,oneof"`
}

func (*BlockResponsePayload_Block) isBlockResponsePayload_Response() {}

func (*BlockResponsePayload_ErrorCode) isBlockResponsePayload_Response() {}

func (m *BlockResponsePayload) GetResponse() isBlockResponsePayload_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *BlockResponsePayload) GetBlock() *Block {
	if x, ok := m.GetResponse().(*BlockResponsePayload_Block); ok {
		return x.Block
	}
	return nil
}

func (m *BlockResponsePayload) GetErrorCode() *Error {
	if x, ok := m.GetResponse().(*BlockResponsePayload_ErrorCode); ok {
		return x.ErrorCode
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BlockResponsePayload) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BlockResponsePayload_Block)(nil),
		(*BlockResponsePayload_ErrorCode)(nil),
	}
}

type Error struct {
	Code                 Error_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Error_ErrorCode" json:"code,omitempty"`
	Desc                 string          `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() Error_ErrorCode {
	if m != nil {
		return m.Code
	}
	return Error_NO_FOUND
}

func (m *Error) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type QuorumCertificate struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SignatureAggregate   []byte       `protobuf:"bytes,2,opt,name=signatureAggregate,proto3" json:"signatureAggregate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QuorumCertificate) Reset()         { *m = QuorumCertificate{} }
func (m *QuorumCertificate) String() string { return proto.CompactTextString(m) }
func (*QuorumCertificate) ProtoMessage()    {}
func (*QuorumCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *QuorumCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuorumCertificate.Unmarshal(m, b)
}
func (m *QuorumCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuorumCertificate.Marshal(b, m, deterministic)
}
func (m *QuorumCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuorumCertificate.Merge(m, src)
}
func (m *QuorumCertificate) XXX_Size() int {
	return xxx_messageInfo_QuorumCertificate.Size(m)
}
func (m *QuorumCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_QuorumCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_QuorumCertificate proto.InternalMessageInfo

func (m *QuorumCertificate) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QuorumCertificate) GetSignatureAggregate() []byte {
	if m != nil {
		return m.SignatureAggregate
	}
	return nil
}

type Block struct {
	Header               *BlockHeader       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Cert                 *QuorumCertificate `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	Data                 *BlockData         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetCert() *QuorumCertificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *Block) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

type BlockHeader struct {
	ParentHash           []byte   `protobuf:"bytes,1,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	DataHash             []byte   `protobuf:"bytes,2,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *BlockHeader) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockData) Reset()         { *m = BlockData{} }
func (m *BlockData) String() string { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()    {}
func (*BlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *BlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockData.Unmarshal(m, b)
}
func (m *BlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockData.Marshal(b, m, deterministic)
}
func (m *BlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockData.Merge(m, src)
}
func (m *BlockData) XXX_Size() int {
	return xxx_messageInfo_BlockData.Size(m)
}
func (m *BlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockData proto.InternalMessageInfo

func (m *BlockData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterEnum("Error_ErrorCode", Error_ErrorCode_name, Error_ErrorCode_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*HelloPayload)(nil), "HelloPayload")
	proto.RegisterType((*ProposalPayload)(nil), "ProposalPayload")
	proto.RegisterType((*BlockRequestPayload)(nil), "BlockRequestPayload")
	proto.RegisterType((*BlockResponsePayload)(nil), "BlockResponsePayload")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*QuorumCertificate)(nil), "QuorumCertificate")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*BlockHeader)(nil), "BlockHeader")
	proto.RegisterType((*BlockData)(nil), "BlockData")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5f, 0x6f, 0xda, 0x30,
	0x10, 0x27, 0x10, 0x5a, 0x72, 0x49, 0xdb, 0xd4, 0xab, 0x26, 0x56, 0x55, 0x1d, 0xb2, 0xaa, 0x0a,
	0xed, 0x21, 0x95, 0xd8, 0x27, 0x80, 0x36, 0x13, 0xd2, 0x58, 0x43, 0x0d, 0x5d, 0xa5, 0xbd, 0x54,
	0x06, 0xdc, 0x90, 0x2d, 0xe0, 0xcc, 0x71, 0x1e, 0x78, 0xda, 0xf7, 0xdc, 0xa7, 0x99, 0xec, 0xfc,
	0x21, 0xd3, 0x26, 0x6d, 0x2f, 0x89, 0xef, 0x77, 0x77, 0xbf, 0xbb, 0xf3, 0xfd, 0x0c, 0x47, 0x1b,
	0x96, 0xa6, 0x34, 0x64, 0x5e, 0x22, 0xb8, 0xe4, 0xe7, 0x6f, 0x42, 0xce, 0xc3, 0x98, 0xdd, 0x68,
	0x6b, 0x91, 0xbd, 0xdc, 0xd0, 0xed, 0x2e, 0x77, 0xe1, 0x9f, 0x06, 0x1c, 0x7e, 0xca, 0x83, 0x51,
	0x1f, 0x4c, 0xb9, 0x4b, 0x58, 0xd7, 0xe8, 0x19, 0xfd, 0xe3, 0xc1, 0x99, 0x57, 0xe0, 0xe5, 0x7f,
	0xbe, 0x4b, 0x18, 0xd1, 0x11, 0xe8, 0x02, 0xac, 0x34, 0x0a, 0xb7, 0x54, 0x66, 0x82, 0x75, 0x9b,
	0x3d, 0xa3, 0xef, 0x90, 0x3d, 0x80, 0x3c, 0x38, 0x4c, 0xe8, 0x2e, 0xe6, 0x74, 0xd5, 0x6d, 0xf5,
	0x8c, 0xbe, 0x3d, 0x38, 0xf3, 0xf2, 0x06, 0xbc, 0xb2, 0x01, 0x6f, 0xb8, 0xdd, 0x91, 0x32, 0x08,
	0x3f, 0x81, 0x5d, 0x2b, 0x81, 0x2c, 0x68, 0x8f, 0xfd, 0xc9, 0x24, 0x70, 0x1b, 0xa8, 0x03, 0xe6,
	0xe7, 0x60, 0xee, 0xbb, 0x06, 0x72, 0xa0, 0x33, 0x25, 0xc1, 0x34, 0x98, 0x0d, 0x27, 0x6e, 0x13,
	0x9d, 0xc2, 0xd1, 0x68, 0x12, 0xdc, 0x7e, 0x7c, 0x26, 0xfe, 0xc3, 0xa3, 0x3f, 0x9b, 0xbb, 0x2d,
	0x84, 0xe0, 0xb8, 0x84, 0x66, 0xd3, 0xe0, 0x7e, 0xe6, 0xbb, 0x26, 0x1e, 0x80, 0x33, 0x66, 0x71,
	0xcc, 0xa7, 0x79, 0x21, 0x84, 0xc1, 0x59, 0x2b, 0xbb, 0xa8, 0xa6, 0x07, 0xb5, 0xc8, 0x6f, 0x18,
	0x7e, 0x82, 0x93, 0xa9, 0xe0, 0x09, 0x4f, 0x69, 0x5c, 0xa6, 0x5d, 0x83, 0xb9, 0x64, 0x42, 0xea,
	0x70, 0x7b, 0x80, 0xbc, 0x87, 0x8c, 0x8b, 0x6c, 0x73, 0xcb, 0x84, 0x8c, 0x5e, 0xa2, 0x25, 0x95,
	0x8c, 0x68, 0x3f, 0xba, 0x80, 0xf6, 0x22, 0xe6, 0xcb, 0x6f, 0xfa, 0x46, 0xec, 0xc1, 0x81, 0x37,
	0x52, 0x16, 0xc9, 0x41, 0x3c, 0x84, 0x57, 0xb9, 0xcd, 0xbe, 0x67, 0x2c, 0x95, 0x25, 0x39, 0x02,
	0x73, 0x4d, 0xd3, 0xb5, 0x26, 0x77, 0x88, 0x3e, 0xa3, 0xd7, 0x70, 0xb0, 0x66, 0x51, 0xb8, 0x96,
	0x9a, 0xa9, 0x4d, 0x0a, 0x0b, 0x7f, 0x85, 0xb3, 0x82, 0x22, 0x4d, 0xf8, 0x36, 0x65, 0x25, 0xc7,
	0x65, 0x59, 0xd8, 0xa8, 0x17, 0x1e, 0x37, 0x8a, 0xd2, 0xe8, 0x1a, 0x2c, 0x26, 0x04, 0x17, 0xb7,
	0x7c, 0xc5, 0xaa, 0xe6, 0x7c, 0x85, 0x8c, 0x1b, 0x64, 0xef, 0x1a, 0x01, 0x74, 0x44, 0x41, 0x8d,
	0x37, 0xd0, 0xd6, 0x11, 0xe8, 0x0a, 0xcc, 0xa5, 0xca, 0xcb, 0x55, 0xe1, 0xe6, 0x79, 0xf9, 0x57,
	0x25, 0x11, 0xed, 0x55, 0x63, 0xac, 0x58, 0xba, 0xd4, 0xec, 0x16, 0xd1, 0x67, 0xfc, 0x0e, 0xac,
	0x2a, 0x4c, 0x2d, 0xf0, 0x3e, 0x78, 0xfe, 0x10, 0x3c, 0xde, 0xdf, 0xb9, 0x0d, 0x74, 0x02, 0xf6,
	0x68, 0x78, 0x57, 0xad, 0xcf, 0xc0, 0x11, 0x9c, 0xfe, 0x71, 0xad, 0xe8, 0x4a, 0xdd, 0x03, 0x5d,
	0x31, 0x51, 0x0c, 0xe6, 0x14, 0x83, 0x69, 0x8c, 0x14, 0x3e, 0xe4, 0x01, 0xaa, 0xb4, 0x37, 0x0c,
	0x43, 0xc1, 0x42, 0x2a, 0x4b, 0x55, 0xfe, 0xc5, 0x83, 0x33, 0x68, 0x6b, 0x9a, 0xff, 0xa4, 0x2f,
	0xb7, 0xdf, 0xfc, 0xc7, 0xf6, 0x2f, 0xc1, 0x5c, 0x51, 0x49, 0x0b, 0xc9, 0x43, 0xce, 0x75, 0x47,
	0x25, 0x25, 0x1a, 0xc7, 0x3f, 0xc0, 0xae, 0xd1, 0xa3, 0x4b, 0x80, 0x84, 0x0a, 0xb6, 0x95, 0xe3,
	0xfd, 0xf6, 0x6b, 0x08, 0x3a, 0x87, 0x8e, 0x4a, 0xd3, 0xde, 0x7c, 0x96, 0xca, 0xae, 0xe9, 0xa3,
	0x55, 0xd7, 0x87, 0x7a, 0x96, 0x32, 0xda, 0xb0, 0x54, 0xd2, 0x4d, 0xd2, 0x35, 0x7b, 0x46, 0xbf,
	0x45, 0xf6, 0x00, 0x7e, 0x0b, 0x56, 0xd5, 0x93, 0xde, 0x97, 0xea, 0xb6, 0x90, 0x9d, 0x3a, 0x8f,
	0xcc, 0x2f, 0xcd, 0x64, 0xb1, 0x38, 0xd0, 0x8f, 0xf4, 0xfd, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x70, 0x5a, 0x41, 0x86, 0x44, 0x04, 0x00, 0x00,
}
