Hotstuff:
  CommitteeSize: 4
  Me: 0
  Delta: 10000
  BlockDelta: 1000
  SeedPath:	static/seed.json
Network:
  MinPeerThreshold: 3
  ReconnectPeriod: 10000
  ConnectionTimeout: 3000
Storage:
  Dir: /var/folders/m7/c56_pk2n0dj4xbplcndc9d140000gn/T/
Static:
  Dir: /Users/dabasov/Projects/gagarin/network/static
Log:
  Level: INFO
Plugins:
  - Address: 'localhost:9380'
    Interfaces: ['OnBlockCommit', 'OnReceiveProposal', 'OnNewBlockCreated']
  - Address: 'localhost:9380'
    Interfaces: ['OnBlockCommit']
Rpc:
  Address: 'localhost:9480'
  MaxConcurrentStreams: 10